basePath: /api/v1
definitions:
  elastic.Instance:
    properties:
      downcount:
        type: integer
      hostname:
        type: string
      ip:
        type: string
      key:
        type: string
      name:
        type: string
      port:
        type: string
      status:
        type: string
      timestamp:
        type: string
      zone:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: seungnyeong@wemakeprice.com
    name: CERT팀 김승녕 매니저
    url: http://stash.wemakeprice.com
  description: wkms alert 서버입니다.
  license:
    name: 위메프 CERT팀 제공
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: wkms-alert
  version: "1.0"
paths:
  /job/instance:
    get:
      consumes:
      - application/json
      description: 현재 실행되고 있는 잡을 알수있음.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/elastic.Instance'
      summary: Get All Job
  /job/start:
    get:
      consumes:
      - application/json
      description: monitor.id를 입력하세요
      parameters:
      - description: Start Cron Job
        in: query
        items:
          type: string
        name: monitorId
        required: true
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: job ok
          schema:
            type: string
      summary: Job 스케줄 실행
  /users/{username}:
    get:
      consumes:
      - application/json
      description: username을 입력하세요
      parameters:
      - description: Get One User
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: job ok
          schema:
            type: string
      summary: 사용자 조회
  /users/list:
    get:
      consumes:
      - application/json
      description: 관리자 전체 조회
      produces:
      - application/json
      responses:
        "200":
          description: job ok
          schema:
            type: string
      summary: 관리자 전체 조회
swagger: "2.0"
