basePath: /api/v1
definitions:
  swagger.Param:
    properties:
      ipv4:
        type: string
    type: object
  swagger.httpResponse:
    properties:
      count:
        type: integer
      message:
        type: string
      result: {}
    type: object
host: 10.107.12.65:8081
info:
  contact:
    email: secutech@wemakeprice.com
    name: 보안기술실 메일 전송
  description: wkms alert moddule
  license:
    name: 위메프 CERT팀 제공
    url: https://stash.wemakeprice.com/projects/SECUTECH/repos/wkms-alert/browse
  termsOfService: https://confluence.wemakeprice.com/pages/viewpage.action?pageId=206230173
  title: wkms-alert module
  version: "1.0"
paths:
  /job/delete/{key}:
    delete:
      consumes:
      - application/json
      description: key를 입력하세요
      parameters:
      - description: Remove Instance
        in: path
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.httpResponse'
      summary: Alert Instance 삭제
      tags:
      - 스케줄
  /job/list:
    get:
      consumes:
      - application/json
      description: 현재 실행되고 있는 잡을 알수있음.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.httpResponse'
      summary: Alerting 이 되고 있는 인스턴스 전체 확인.
      tags:
      - 스케줄
  /job/start:
    post:
      consumes:
      - application/json
      description: ipv4를 입력하세요
      parameters:
      - description: Alerting 설정할 인스턴스 ipv4를 입력하세요
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/swagger.Param'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.httpResponse'
      summary: Alert Instance 등록
      tags:
      - 스케줄
  /users/{username}:
    get:
      consumes:
      - application/json
      description: username을 입력하세요
      parameters:
      - description: Get One User
        in: path
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.httpResponse'
      summary: 사용자 조회
      tags:
      - 계정
  /users/list:
    get:
      consumes:
      - application/json
      description: WKMS 관리자 전체 조회
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/swagger.httpResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/swagger.httpResponse'
      summary: WKMS 관리자 전체 조회
      tags:
      - 계정
swagger: "2.0"
